version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    container_name: worker
    command: ["celery", "-A", "app.worker.celery_app", "worker", "-l", "info"]
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "app.worker.celery_app", "beat", "-l", "info"]
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: fastapi_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: