"""Initial

Revision ID: 5ef64cca7f7c
Revises: 
Create Date: 2025-05-07 08:19:04.100231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef64cca7f7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # wallet_status_enum = sa.Enum('NEW', 'PENDING', 'PROCESSED', 'FAIL', name='walletstatus')
    # transaction_status_enum = sa.Enum('NEW', 'PENDING', 'PROCESSED', 'FAIL', name='transactionstatus')
    #
    # wallet_status_enum.create(op.get_bind(), checkfirst=True)
    # transaction_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PENDING', 'PROCESSED', 'FAIL', name='walletstatus'), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'network', name='uniq_currency_network')
    )
    op.create_index(op.f('ix_whitelist_id'), 'whitelist', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PENDING', 'PROCESSED', 'FAIL', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_whitelist_id'), table_name='whitelist')
    op.drop_table('whitelist')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    transaction_status_enum = sa.Enum(name='transactionstatus')
    wallet_status_enum = sa.Enum(name='walletstatus')

    transaction_status_enum.drop(op.get_bind(), checkfirst=True)
    wallet_status_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
